import Head from 'next/head'
import HomeComponent from '../components/HomeComponent/HomeComponent'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeComponent></HomeComponent>
      </main>
    </div>
  )
}
